# Generated by Django 3.1.7 on 2021-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
