# Generated by Django 3.1.7 on 2021-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210306_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bug',
            name='stepstoreproduce',
            field=models.TextField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
