# Generated by Django 3.1.7 on 2021-03-07 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_foreingkeys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='bug',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 17, 55, 22, 92459)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 17, 55, 22, 84453)),
        ),
    ]
