# Generated by Django 3.1.7 on 2021-03-14 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20210307_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477)),
        ),
        migrations.AlterField(
            model_name='bug',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477)),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477))),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477))),
                ('priority', models.CharField(choices=[('P4', 'Low'), ('P3', 'Medium'), ('P2', 'High'), ('P1', 'Critical')], default='P4', max_length=2)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Enhancements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477))),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 19, 23, 914477))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
